#This file is an example of an environment file for defining the isolated
#networks and related parameters.
resource_registry:
  # Network Interface templates to use (these files must exist)
  OS::TripleO::BlockStorage::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/controller.yaml
  OS::TripleO::ObjectStorage::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/swift-storage.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/ceph-storage.yaml

parameter_defaults:
  # This section is where deployment-specific configuration is done
  # Customize the IP subnets to match the local environment
  InternalApiNetCidr: 10.35.140.0/27
  StorageNetCidr: 10.35.140.32/27
  StorageMgmtNetCidr: 192.168.2.0/24
  TenantNetCidr: 192.168.1.0/24
  ExternalNetCidr: 10.35.140.64/27
  # CIDR subnet mask length for provisioning network
  ControlPlaneSubnetCidr: '24'
  # Customize the IP ranges on each network to use for static IPs and VIPs
  InternalApiAllocationPools: [{'start': '10.35.140.2', 'end': '10.35.140.29'}]
  StorageAllocationPools: [{'start': '10.35.140.33', 'end': '10.35.140.61'}]
  StorageMgmtAllocationPools: [{'start': '192.168.2.1', 'end': '192.168.2.200'}]
  TenantAllocationPools: [{'start': '192.168.1.1', 'end': '192.168.1.200'}]
  # Leave room if the external network is also used for floating IPs
  ExternalAllocationPools: [{'start': '10.35.140.66', 'end': '10.35.140.89'}]
  # Gateway router for the external network
  ExternalInterfaceDefaultRoute: 10.35.140.94
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 192.168.0.254
  # Generally the IP of the Undercloud
  EC2MetadataIp: 192.168.0.4
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["10.35.28.28","10.35.28.1","8.8.8.8"]
  # Customize the VLAN IDs to match the local environment
  InternalApiNetworkVlanID: 393
  StorageNetworkVlanID: 394
  StorageMgmtNetworkVlanID: 13
  TenantNetworkVlanID: 12
  ExternalNetworkVlanID: 395
  # Set to empty string to enable multiple external networks or VLANs
  NeutronExternalNetworkBridge: "''"
  # Customize bonding options, e.g. "mode=4 lacp_rate=1 updelay=1000 miimon=100"
  BondInterfaceOvsOptions: "mode=active-backup"
